apiVersion: core.eda.nokia.com/v1
kind: Manifest
metadata:
  name: bottom-toolbar
spec:
  appInfo:
    categories:
      - networking
    documentation: bottom_toolbar/docs
  author: eda-labs
  supportedEndpoints:
    - "srl:25.*.*"
    - "srl:26.*.*"
  dependencies:
    - file:
        path: utils
    - file:
        path: common
    - file:
        path: core
    - file:
        path: bottom_toolbar/api/v1alpha1/pysrc
    - file:
        path: bottom_toolbar/intents
  description: Set some crazy message in the CLI's bottom toolbar of the SR Linux nodes.
  group: bottom-toolbar.eda.labs
  image: ghcr.io/eda-labs/bottom-toolbar:v0.1.0
  supportedCoreVersions:
    - v4.0.0-0
    - v5.0.0-0
    - v6.0.0-0
  title: Bottom Toolbar
  version: v1alpha1
  components:
    - crd:
        api:
          expose: readWrite
        path: bottom_toolbar/crds/bottom-toolbar.eda.labs_bottomtoolbars.yaml
        schema: bottom_toolbar/openapiv3/eda_oas_bottom-toolbar.eda.labs_bottomtoolbars.json
        ui:
          category: Management
          name: Bottom Toolbars
    - script:
        path: bottom_toolbar/intents/bottomtoolbar/config_intent.py
        trigger:
          kind: BottomToolbar
        type: config
